### ISSUE TITLE
samsung note8 7.1.1 msm8998 can not boot locat.txt

### ISSUE THREAD

**Issue by ucxl** [rovo89/XposedBridge#210] opened 2017-10-17 02:34 UTC
samsung note8 7.1.1 msm8998 can not boot
Already available  locat.txt

thanks 

[logcat.txt](https://github.com/rovo89/XposedBridge/files/1389587/logcat.txt)

**Comment by rovo89** [comment] 2017-10-30 11:27
Duplicate of https://github.com/rovo89/Xposed/issues/273

**Closed as completed by rovo89** 2017-10-30 11:27 UTC
Labels: duplicate
