### ISSUE TITLE
Resource forwarding doesn't work reliably

### ISSUE THREAD

**Issue by tonyp** [rovo89/XposedBridge#38] opened 2015-04-12 14:34 UTC
I know this has been reported before at xda but I'd like to make sure that it doesn't get lost.

So, I tried two different approaches to get my resources into the ROM.
1) Injecting a fake ID, then trying to access the ID.
Basically this approach: http://forum.xda-developers.com/showpost.php?p=53918940&postcount=4

2) Using the resparam.res.setReplacement method with modRes.fwd, following the tutorial for replacing complex resources.

**Both methods work totally fine on my Nexus 5 with AOSP. But especially users with CM12 are reporting that the icon replacement doesn't work.**
With method 1 they see no icon at all, with method 2 they still have the original, not replaced icon.
I couldn't find a suitable workaround yet and am a bit lost on how to approach these issues until Xposed fixes the API.

Here are some more comments about the issue:
http://forum.xda-developers.com/xposed/devs-resource-forwarding-lollipop-t3033346

If you need full code examples I can provide them, but as I'm just using standard code I didn't yet see a need for that.

**Comment by rovo89** [comment] 2015-04-12 15:53
Just to be sure: Is this issue limited to Lollipop or do you experience the same problems on older Android releases as well?

**Comment by tonyp** [comment] 2015-04-12 16:00
As far as I know it's Lollipop only.
While I didn't try it out with Kitkat I did search through loads of Xposed threads at xda and couldn't find a single reference to (framework related) problems in that matter on Kitkat, only with the new alpha.

**Comment by tonyp** [comment] 2015-04-12 16:03
I'll link in @C3C0 as has a similiar in his:

**Comment by tonyp** [comment] 2015-04-12 16:04
Sorry about the double post. 
I'll link in @C3C0 as he stated a similar issue in his "What's currently missing in version for Lollipop" for Gravitybox:
"No H+ indicator for mobile data for now as there seem to be some issues with Xposed Framework fake resource ID injection".

Maybe he has some further input.

**Comment by C3C0** [comment] 2015-04-12 16:22
I have no further input apart from the one at XDA @tonyp mentioned. There's also a logcat .

**Comment by rovo89** [comment] 2015-04-12 19:13
I tried this:

``` java
if (resparam.packageName.equals("com.android.settings")) {
    XModuleResources moduleRes = XModuleResources.createInstance(MODULE_PATH, resparam.res);
    resparam.res.setReplacement("com.android.settings", "drawable", "ic_settings_wireless" , moduleRes.fwd(R.drawable.test));
}
```

And indeed, it has no effect on CM12. As I wasn't sure whether I tried to replace the correct drawable, I have checked how the drawable is used, and finally found out that the `Resources` class has new variants of `getDrawable()` and `getDrawableForDensity()` now, which take a `theme` parameter. In CM, there is an additional, hidden variant. So proabably, I will need to override these variants in `XResources` as well.

**Comment by Mikanoshi** [comment] 2015-04-12 20:00
Nice that this problem is finally being dealt with, although I've already made a workaround for it in my module... `getDrawable()` and `getDrawableForDensity()` with `theme` are there on HTC too, hope there is no hidden stuff :)

**Comment by C3C0** [comment] 2015-04-12 20:01
Great. I assume it has nothing to do with the other issue, though: injecting fake resource ID  where fake id is forwarded to module resource.

**Comment by tonyp** [comment] 2015-04-12 21:24
Yes, a fix for that would be very welcome! 
I guess there's no easy workaround until the issue has been fixed framework side?
A hook into the Ressource class could be possible, but that might not be too smart performance-wise - and not worth the time when a Xposed update is coming soon.

Anyways, I just had a look at the documentation and this might be interesting for Android 5.1:
"This method was deprecated in API level 22. Use getDrawable(int, Theme) instead."
http://developer.android.com/reference/android/content/res/Resources.html#getDrawable(int)

**Comment by rovo89** [comment] 2015-04-14 06:47
> I assume it has nothing to do with the other issue, though: injecting fake resource ID where fake id is forwarded to module resource.

This might still be related. The fake ID can only be resolved by `XResources`. But as the new variants are not overridden yet, they are handled by the original `Resources` class, which fails.

In order to fix this, I will need to change my project layout a bit, so I will need some more time...

**Comment by C3C0** [comment] 2015-04-14 06:51
Great. Thank you very much for taking time to took into it.

**Comment by tonyp** [comment] 2015-04-14 08:02
No worries about the time, at least it's on the todo list now. I guess reporting issues at Github is way smarter than at xda, which is just over flooded. Thanks for being so responsive here.

As you know the internal processes best: do you see a workaround for current modules? 
While hooking into getDrawables and overwriting the handling of the supportComposedIcons boolean of the hidden method doesn't seem complicated I doubt it has any effect as the Xposed Bridge will call the underlying internal functions. But maybe there's another way?

**Comment by rovo89** [comment] 2015-04-16 21:51
Can you test this one please? You have to put the file to `/system/framework/XposedBridge.jar`.
https://www.dropbox.com/s/3mxagaj0np1sg1z/XposedBridge-Issue38.jar?dl=0

**Comment by tonyp** [comment] 2015-04-16 22:09
When I use the new framework on my Nexus 5 with AOSP the icon replacement which worked before suddenly does not anymore. Restoring the old framework brings it back.

Did you test it on CM12? If not I need to flash it to my old device which will take a bit more time.

**Comment by rovo89** [comment] 2015-04-16 22:30
I tested it on only on CM12, no time to test it on other ROMs yet.

**Comment by tonyp** [comment] 2015-04-16 23:02
Ok, I'm using the Stock AOSP 5.0.2 ROM on the N5 and it breaks the icon replacement which did work here with the alpha2.
If I can provide any other input let me know.

Update: I tested it with CM12 on my LG 2x and it doesn't seem to fix the issue, either. It's a build from the beginning of march and quite unstable, though - but the latest version available for that old phone.
I'm testing with my True Silent Mode for Lollipop module, when the replace fails it will show a TTY icon rather than one indicating the silent mode:
https://play.google.com/store/apps/details?id=com.thetonyp.truesilentmode

**Comment by roberto-sartori-gl** [comment] 2015-04-17 07:01
I've also tried the new XposedBridge, on CM12 (nightly, April 15). It seems to work with one of my module, that is very simple ( https://github.com/robertosartori/BlackTwitter/blob/master/src/com/robertogl/BlackTwitter/Main.java )
With old XposedBridge it doesn't work on Lollipop (but with the same apk it works on KitKat). With the new jar it works also on Lollipop. I've to say that some lines worked also on Lollipop before the new jar, like in that Main.java that i've linked 

"resparam.res.setReplacement("com.twitter.android", "color", "white", modRes.fwd(R.color.white));" 

worked, but 

" resparam.res.setReplacement("com.twitter.android", "color", "common_signin_btn_default_background", modRes.fwd(R.color.common_signin_btn_default_background));"

 worked only on KitKat. Now they work on all system.

I've tested also the True Silent Mode module and i see the TTY icon with all Bridge.jar, but i don't know if the problem is the module (like i said, with my simple module it seems to work).

**Comment by C3C0** [comment] 2015-04-17 07:19
Happy to say that injecting fake resource IDs pointing to module drawables seem to be working fine with new XposedBridge. ( code: https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/StatusbarSignalCluster.java#L183 )
Nexus 5, stock 5.0.1

Direct drawable replacement (code: https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModNavigationBar.java#L270 ) works too. But that also worked in previous version of XposedBridge for me.

Thanks for your efforts, rovo.

**Comment by tonyp** [comment] 2015-04-17 15:01
Oh, I think I tracked down the issue with my True Silent Mode module.
The XposedBridgeAPI was compiled rather than referenced in the gradle file in Android Studio :open_mouth:
So I guess the app stopped working because of conflicting libraries.
Now the new library works with AOSP again, sorry about that.

Although it still doesn't work here on CM12:
This is the code the module is using, it does look correct.
I'll investigate it further during the weekend.

```
public void initZygote(StartupParam startupParam) throws Throwable {
    MODULE_PATH = startupParam.modulePath;
}
public void handleInitPackageResources(XC_InitPackageResources.InitPackageResourcesParam resparam) throws Throwable {
    if ("com.android.systemui".equals(resparam.packageName)) {
        XModuleResources modRes = XModuleResources.createInstance(MODULE_PATH, resparam.res);            
        int icon = R.drawable.stat_sys_ringer_silent_kitkat;
        resparam.res.setReplacement(PACKAGE_NAME, "drawable", "stat_sys_tty_mode", modRes.fwd(icon));
    }
}
```

**Comment by C3C0** [comment] 2015-04-17 17:37
@tonyp
Try using icon (int) directly instead of forwarder.

**Comment by tonyp** [comment] 2015-04-19 16:25
Okay, I did some more tests but the resource forwarding still only works on AOSP for me, not on CM12.
To make it easier I put the relevant code into a small test app, this is the main class:
https://github.com/tonyp/XposedReplacerTest/blob/master/app/src/main/java/com/thetonyp/xposedreplacertest/XposedReplacerTest.java

As I said the CM12 build for the LG 2x is an unofficial, hacked together build (but the only one available), so it might be due to that.
Maybe someone running a newer/stable CM12 build could tell me if the icon replacement works for him with this apk.
https://dl.dropboxusercontent.com/u/2478159/temp/XposedReplacerTest-debug.apk
Edit: When the replacment works you'll see a bell icon in the statusbar, when it doesn't an icon with the letters TTY.

Full source of the test app: https://github.com/tonyp/XposedReplacerTest

I don't really see where my code differs from the ones people posted here which do work with the new library.

@C3C0: thanks, although using icon without the ressource forwarder won't work - but as you deleted your comment I guess you came to the same conclusion.

**Comment by C3C0** [comment] 2015-04-19 16:35
@tonyp
Yes, I deleted it immediately after posting as I realized it was a nonsense.

**Comment by roberto-sartori-gl** [comment] 2015-04-19 16:45
> Okay, I did some more tests but the resource forwarding still only works on AOSP for me, not on CM12.
> To make it easier I put the relevant code into a small test app, this is the main class:
> https://github.com/tonyp/XposedReplacerTest/blob/master/app/src/main/java/com/thetonyp/xposedreplacertest/XposedReplacerTest.java
> 
> As I said the same CM12 build for the LG 2x is an unofficial, hacked together build (but the only one available), so it might be due to that.
> Maybe someone running a newer/stable CM12 build could tell me if the icon replacement works for him with this apk.
> https://dl.dropboxusercontent.com/u/2478159/temp/XposedReplacerTest-debug.apk
> 
> Full source of the test app: https://github.com/tonyp/XposedReplacerTest
> 
> I don't really see where my code differs from the ones people posted here which do work with the new library.

Tried, this isn't working on last CM12 nightly (I9505), like the full True Silent Mode module (the icon replacement part).

**Comment by tonyp** [comment] 2015-04-19 16:48
@robertosartori thank you for testing! Maybe @rovo89 could do some further debugging why this doesn't work if he finds some time.
I really hope I didn't do any stupid mistake, but as the replacement works with AOSP I think code-wise everything should be correct.
As I already wrote, the test apps source code is here: https://github.com/tonyp/XposedReplacerTest

**Comment by rovo89** [comment] 2015-04-23 21:30
@tonyp Your example is more complex than it looks. The icon isn't used in the SystemUI process, but passed to the SystemBarService, which then loads the resources. At first, I thought that maybe the package name cannot be determined correctly in the other process. But then I found out that there is now a `getTopLevelThemedResources()` method that also needs to be hooked for cases like yours. I have implemented the basics for that and it seems to work, but I need to look at this in more detail.

**Comment by rovo89** [comment] 2015-04-25 20:44
Actually, the method is CM-specific, but has been introduced in CM11 already..

@tonyp Could you test this please? https://www.dropbox.com/s/3mxagaj0np1sg1z/XposedBridge-Issue38.jar?dl=0
It's working fine for me on CM12 with your example and my own. Not tested on AOSP yet.

**Comment by C3C0** [comment] 2015-04-25 20:54
Direct drawable replacement as well as referencing via fake id seems to work OK on N5 stock 5.0.1.

**Comment by roberto-sartori-gl** [comment] 2015-04-25 20:56
I've tested on CM12 and the True Silent Mode module. Now it seems to work without problems.
Tested also the XposedReplacerTest by @tonyp and this is also working.

**Comment by tonyp** [comment] 2015-04-26 00:41
@rovo89 Confirmed working with CM12 and AOSP 5.0.2.
Just in case I tested both, addResource() and adding fake IDs - no issues whatsoever.

Ship it :)

**Comment by rovo89** [comment] 2015-04-26 11:52
Thanks for testing! It will be fixed with XposedBridge v63+. I'll see what else I can do today and then release an update.

**Closed as completed by rovo89** 2015-04-26 11:52 UTC
Labels: bug
