### ISSUE TITLE
Zygote: Unknown command line argument: --zygote-aslr-agent

### ISSUE THREAD

**Issue by tbe** [rovo89/XposedBridge#205] opened 2017-10-14 10:39 UTC
* Device: SM-G920F
* Build: G920FXXU5EQH7

In the Xposed logs, the "started xposed" line pops up every two seconds.

From the system log:
```
10-14 12:37:03.922 28816 28816 E Zygote  : Zygote died with exception
10-14 12:37:03.922 28816 28816 E Zygote  : java.lang.RuntimeException: Unknown command line argument: --zygote-aslr-agent
10-14 12:37:03.922 28816 28816 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1356)
10-14 12:37:03.922 28816 28816 E Zygote  :      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-14 12:37:03.922 28816 28816 D AndroidRuntime: Shutting down VM
10-14 12:37:03.922 28816 28816 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: main
10-14 12:37:03.922 28816 28816 E AndroidRuntime: java.lang.RuntimeException: Unknown command line argument: --zygote-aslr-agent
10-14 12:37:03.922 28816 28816 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1356)
10-14 12:37:03.922 28816 28816 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-14 12:37:03.928 28816 28816 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 88)
10-14 12:37:03.928 28816 28816 E ServiceManager: error in getService
10-14 12:37:03.928 28816 28816 E ServiceManager: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.os.BinderProxy.transactNative(Native Method)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.os.BinderProxy.transact(Binder.java:628)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.os.ServiceManager.getService(ServiceManager.java:66)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3477)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:3476)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.util.Singleton.get(Singleton.java:34)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:97)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:130)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-14 12:37:03.928 28816 28816 E ServiceManager:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
10-14 12:37:03.929 28816 28816 E AndroidRuntime: Error reporting crash
10-14 12:37:03.929 28816 28816 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference
10-14 12:37:03.929 28816 28816 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:130)
10-14 12:37:03.929 28816 28816 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-14 12:37:03.929 28816 28816 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
```

**Comment by rovo89** [comment] 2017-10-16 07:33
Thanks for the report! I had seen this additional argument before. Not sure if the same logic can (easily) be ported, otherwise at least those error messages should be suppressed. Would be interesting to know what exactly the flag does. Maybe @wanam could look at this?

On this topic: https://copperhead.co/blog/2015/05/11/aslr-android-zygote

**Comment by wanam** [comment] 2017-10-16 11:49
The only occurrence i have seen of "aslr" on my gs7 logs:
`10-03 10:06:20.750  3296  3296 I Enhanced Zygote ASLR: DISABLED!`
So i think this feature was disabled on my device, and it seems to be related to Knox, can be activated with this prop:
`ro.knox.enhance.zygote.aslr=1`

I don't have my gs7 on my hands now, i will update its firmware tomorrow and see if i can reproduce it.

No idea what the flag would trigger, but it is a sec layer that should be randomizing the location where system executables are loaded into memory.

**Comment by wanam** [comment] 2017-10-17 09:56
I managed to reproduce it by enabling this prop "ro.knox.enhance.zygote.aslr=1":

```
10-17 10:49:08.355  9938  9938 I Enhanced Zygote ASLR: ENABLED!
10-17 10:49:08.374  3933  3976 I Enhanced Zygote ASLR: This app is forked from the original zygote. uid = 1000, seinfo = platform, niceName = com.samsung.android.securitylogagent, abi = arm64-v8a
10-17 10:49:08.389 10014 10014 E Zygote  : v2
10-17 10:49:08.447  9938  9938 E Zygote  : Zygote died with exception
10-17 10:49:08.447  9938  9938 E Zygote  : java.lang.RuntimeException: Unknown command line argument: --zygote-aslr-agent
10-17 10:49:08.447  9938  9938 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1309)
10-17 10:49:08.447  9938  9938 E Zygote  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
10-17 10:49:08.447  9938  9938 D AndroidRuntime: Shutting down VM
10-17 10:49:08.447  9938  9938 E AndroidRuntime: !@*** FATAL EXCEPTION IN SYSTEM PROCESS: main

```
@tbe  I'm surprised why it's been enabled on your device, is it default enabled or you did it manually?

**Comment by rovo89** [comment] 2017-10-17 10:34
I'm wondering if ZygoteInit should handle this flag or app_process. At least they have added a lot of lines to ZygoteInit, the exception is thrown at line 734 instead of 1309 in AOSP: https://android.googlesource.com/platform/frameworks/base.git/+/nougat-mr2-release/core/java/com/android/internal/os/ZygoteInit.java#734

**Comment by ahronshor** [comment] 2017-10-17 13:40
i tested on samsung note 8 with this exception.
and modifying the system/build.prop  ro.knox.enhance.zygote.aslr=1 to 0
solved the problem.
and also the Note8 battery drain problem #259 
tanks @wanam and @rovo89 .

**Comment by Jeffdow85** [comment] 2017-10-19 20:56
@ahronshor awesome mate can confirm working for me too after changing build.prop cod you said thanks so much for sharing and thanks @wanam for directing me to this post. Cheers guys will now be able to share with others too ☺ 👌

**Comment by suirzes** [comment] 2017-10-23 12:31
Guys, noob alert.
@ahronshor, @rovo89 , how this find of yours can be implemented by a noobie? Should i just wait for 88.2?

**Comment by Jeffdow85** [comment] 2017-10-23 14:03
@suirzes if you're on Samsung SDK 25 ANDROID 7.1.1 and facing same issue discussed here. You obviously already have root so find a file Explorer you like that has root capabilities and the file you need to edit is found and this path :root /system/build.prop

Edit with something like droidedit free from play store it has a search feature to help you find the right line of text to edit. Search for:  ro.knox.enhance.zygote.aslr=1

Change the =1 to =0 then save the edited copy to your internal memory then copy and paste it back at the place you first opened the original file in system folder. Set permissions to rw-r--r--  or 644 depending on your root Explorer. If you're still having trouble following those instructions let me know and I'll try do a short video to help out. Or can edit your build prop for you and send it back but it video would probably be more useful if you're really noob and still learning as you can actually see how it's done.

**Comment by suirzes** [comment] 2017-10-23 18:31
@Jeffdow85 thanks for the laydown. I just hit a roadblock while copying. It just will not allow to copy back into system/. Im dumbfounded. Must be Magisk related...
Any tips on that?

**Comment by rovo89** [comment] 2017-10-23 18:32
You might just want to wait for the next Xposed version. It will ignore this setting.

**Comment by suirzes** [comment] 2017-10-23 18:35
If i will not be able to go around it, I will be one hellishly impatient user waiting for next version :)

**Comment by rovo89** [comment] 2017-10-23 20:15
Please try this:
https://www.dropbox.com/s/krotaen0mx53swg/xposed-v88.2-sdk24-arm64-test5.zip?dl=0
https://www.dropbox.com/s/djnlycyjtk8hpnh/xposed-v88.2-sdk25-arm64-test5.zip?dl=0

**Comment by suirzes** [comment] 2017-10-24 15:00
It appears the drain was stopped successfully. Im really grateful! Im literally jumping round with joy.

CPU still about 2-4% more loaded than without framework, but that is understandable, expected and survivable.

Would additional log dump be of any use?

**Comment by Jeffdow85** [comment] 2017-10-25 01:56
@suirzes sorry only just saw this now glad you got it resolved, well done @rovo89 and thanks for your amazing framework 👍

**Comment by HorstiG** [comment] 2017-10-27 21:06
Works perfectly with N 7.1.1 on S7 Edge and S8 Plus, hero2lte and dream2lte, thank you !!!

**Comment by HorstiG** [comment] 2017-10-27 21:07
Booth Note 8 port roms

**Comment by mrprabhjoy** [comment] 2017-10-28 08:48
I have tried new 88.2 SDK25 on note 8 ported rom & works smooth but it breaks outgoing call.

**Comment by OptX** [comment] 2017-10-28 12:12
I'm on a note 8 ported rom, just made a testcall.
All fine here with 88.2 test 5.....

**Comment by HorstiG** [comment] 2017-10-28 12:13
This must be another problem, Xposed runs perfectly on Note 8 Port ROMs

**Comment by mrprabhjoy** [comment] 2017-10-28 12:21
I'm also on note 8 ported rom then why im getting issue in outgoing call.

**Comment by HorstiG** [comment] 2017-10-28 12:31
Wrong ROM, maybe User problem? 😁

**Comment by elesbb** [comment] 2017-10-29 19:42
88.2 test works for Sprint S6 on 7.0. Thanks!

**Comment by elesbb** [comment] 2017-10-30 01:28
Okay so it works but bluetooth is now broken. I have scoured the logcat and nothing is sticking out to me...

Heres the log if it helps.
[log.txt](https://github.com/rovo89/XposedBridge/files/1425702/log.txt)

**Comment by HorstiG** [comment] 2017-10-30 01:39
Bluetooth works also perfectly with my Gear 3 and Bluetooth speakers. S7, S8 and Note 8

**Comment by elesbb** [comment] 2017-10-30 02:20
Yeah realized its not xposed but the action of rebooting my phone breaks bluetooth. So, like, I install my ROM, everything works. Don't do anything, reboot, bluetooth broken. So it was a false positive that I thought it was xposed. My bad :) All is good.

**Comment by rovo89** [comment] 2017-10-30 15:26
Fixed in v88.2.

**Closed as completed by rovo89** 2017-10-30 15:26 UTC
Labels: incompatibility

**Comment by mrprabhjoy** [comment] 2017-10-31 16:42
But i flashed again 88.2 sdk25 on note 8 ported rom but same outgoing call problem. One thing more, in my country I'm using volte network. I think it breaks volte connectivity thats why all guys not getting outgoing call problem who don't use volte. That could be the issue to not able to outgoing call for me.

**Comment by redhusker2017** [comment] 2017-10-31 22:59
Will this work on my Galaxy S6 SM-G920P?
