### ISSUE TITLE
Xiaomi Redmi Note 3 Bootloop - IncompatibleClassChangeError

### ISSUE THREAD

**Issue by jonny133** [rovo89/XposedBridge#82] opened 2016-02-07 13:36 UTC
Getting bootloop on this device, even when Xposed disabled via conf file and resource hooks disabled.

```
--------- beginning of main

--------- beginning of system

I/Xposed  (  308): -----------------

I/Xposed  (  308): Starting Xposed version 80, compiled for SDK 21

I/Xposed  (  308): Device: Redmi Note 3 (Xiaomi), Android version 5.0.2 (SDK 21)

I/Xposed  (  308): ROM: sMiUI v7 6.1.28

I/Xposed  (  308): Build fingerprint: Xiaomi/hennessy/hennessy:5.0.2/LRX22G/6.1.29:user/release-keys

I/Xposed  (  308): Platform: arm64-v8a, 64-bit binary, system server: yes

I/Xposed  (  308): SELinux enabled: yes, enforcing: yes

I/Xposed  (  308): -----------------

I/Xposed  (  308): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH

I/Xposed  (  308): Detected ART runtime

I/Xposed  (  308): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing

E/Xposed  (  308): Error while loading XResources class 'android/content/res/XResources':

E/Xposed  (  308): java.lang.IncompatibleClassChangeError: android.content.res.XResources

E/Xposed  (  308):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)

E/Xposed  (  308):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)

E/Xposed  (  308):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)

E/Xposed  (  308):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)

E/Xposed  (  308):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)

E/Xposed  (  308):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)

E/Xposed  (  308):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)

E/Xposed  (  308):   at boolean de.robv.android.xposed.XposedBridge.initNative() (XposedBridge.java:-2)

E/Xposed  (  308):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:98)

I/Xposed  (  308): Errors during native Xposed initialization

I/Xposed  (  309): -----------------

I/Xposed  (  309): Starting Xposed version 80, compiled for SDK 21

I/Xposed  (  309): Device: Redmi Note 3 (Xiaomi), Android version 5.0.2 (SDK 21)

I/Xposed  (  309): ROM: sMiUI v7 6.1.28

I/Xposed  (  309): Build fingerprint: Xiaomi/hennessy/hennessy:5.0.2/LRX22G/6.1.29:user/release-keys

I/Xposed  (  309): Platform: arm64-v8a, 32-bit binary, system server: no

I/Xposed  (  309): SELinux enabled: yes, enforcing: yes

I/Xposed  (  309): -----------------

I/Xposed  (  309): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH

I/Xposed  (  309): Detected ART runtime

I/Xposed  (  309): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing

E/Xposed  (  309): Error while loading XResources class 'android/content/res/XResources':

E/Xposed  (  309): java.lang.IncompatibleClassChangeError: android.content.res.XResources

E/Xposed  (  309):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)

E/Xposed  (  309):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)

E/Xposed  (  309):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)

E/Xposed  (  309):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)

E/Xposed  (  309):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)

E/Xposed  (  309):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)

E/Xposed  (  309):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)

E/Xposed  (  309):   at boolean de.robv.android.xposed.XposedBridge.initNative() (XposedBridge.java:-2)

E/Xposed  (  309):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:98)

I/Xposed  (  309): Errors during native Xposed initialization


```

**Comment by rovo89** [comment] 2016-02-10 08:02
If Xposed was disabled via config file, you would see a message about it in the log and this crash couldn't happen...
Anyway, please post an unfiltered logcat, I assume there's more information (e.g. with the "art" tag).

**Comment by jonny133** [comment] 2016-02-10 19:57
Right, I meant that the phone still bootloops even when Xposed is disabled, but these logs are from when it isn't disabled. Hope this is more useful thanks rovo89:

**Comment by rovo89** [comment] 2016-02-11 11:20
Thanks. The only additional lines I found were:
`Rejecting re-init on previously-failed class java.lang.Class<android.content.res.XResources>`

Most likely, it's because of the logic to hook the resources. I assume that it will need a bigger change...

**Comment by jonny133** [comment] 2016-02-11 21:11
Is there anything else I can do?

**Comment by rovo89** [comment] 2016-02-19 07:33
I don't think so. Closing this as a duplicate of #61

**Closed as completed by rovo89** 2016-02-19 07:33 UTC
Labels: duplicate
