### ISSUE TITLE
samsung note8 7.1.1  msm8998 can not boot

### ISSUE THREAD

**Issue by ucxl** [rovo89/XposedBridge#208] opened 2017-10-16 06:14 UTC
samsung note8 7.1.1  msm8998 can not boot  Thank God for the restoration 

samsung note8 7.1.1 universal8895 update 88.1 Unsmooth

**Comment by rovo89** [comment] 2017-10-16 06:23
Logs please: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by ucxl** [comment] 2017-10-26 11:39
[logcat.txt](https://github.com/rovo89/XposedBridge/files/1418157/logcat.txt)

**Comment by rovo89** [comment] 2017-10-30 11:27
Duplicate of https://github.com/rovo89/Xposed/issues/273

**Closed as completed by rovo89** 2017-10-30 11:27 UTC
Labels: duplicate, more info needed
