### ISSUE TITLE
NoClassDefFoundError caused by references to classes added in API level 23

### ISSUE THREAD

**Issue by JayT5** [rovo89/XposedBridge#57] opened 2015-08-21 18:15 UTC
The activity of the app I am modifying (Chrome Beta) now contains references to the class `android.app.assist.AssistContent` which was added in API level 23. When I try to call one of the activity's methods I get a NoClassDefFoundError, here's the log:

```
08-21 18:14:34.416 I/Xposed  (  229): -----------------
08-21 18:14:34.417 I/Xposed  (  229): Starting Xposed version 68 (by romracer / 20150727), compiled for SDK 22
08-21 18:14:34.417 I/Xposed  (  229): Device: Nexus 5 (LGE), Android version 5.1.1 (SDK 22)
08-21 18:14:34.417 I/Xposed  (  229): ROM: LMY48B
08-21 18:14:34.417 I/Xposed  (  229): Build fingerprint: google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys
08-21 18:14:34.417 I/Xposed  (  229): Platform: armeabi-v7a, 32-bit binary, system server: yes
08-21 18:14:34.417 I/Xposed  (  229): SELinux enabled: yes, enforcing: yes
08-21 18:14:34.426 I/Xposed  (  229): -----------------
08-21 18:14:34.426 I/Xposed  (  229): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
08-21 18:14:35.032 I/Xposed  (  229): Detected ART runtime
08-21 18:14:35.070 I/Xposed  (  229): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
08-21 18:14:35.403 I/Xposed  (  229): Loading modules from /data/app/com.lemonsqueeze.fakewificonnection-1/base.apk
08-21 18:14:35.622 I/Xposed  (  229):   Loading class com.lemonsqueeze.fakewificonnection.Main
08-21 18:14:35.687 I/Xposed  (  229): Loading modules from /data/app/com.jt5.xposed.chromepie-1/base.apk
08-21 18:14:35.720 I/Xposed  (  229):   Loading class com.jt5.xposed.chromepie.ChromePie
08-21 18:14:35.731 I/Xposed  (  229): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
08-21 18:14:35.747 I/Xposed  (  229):   Loading class ma.wanam.youtubeadaway.Xposed
08-21 18:14:35.756 I/Xposed  (  229): Loading modules from /data/app/net.madnation.sskip-1/base.apk
08-21 18:14:35.780 I/Xposed  (  229):   Loading class net.madnation.sskip.sskip
08-21 18:20:58.175 E/Xposed  ( 5970): java.lang.NoClassDefFoundError: android.app.assist.AssistContent
08-21 18:20:58.175 E/Xposed  ( 5970):   at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.Class.getDexCacheType(Class.java:479)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:191)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.reflect.ArtMethod.getParameterTypes(ArtMethod.java:136)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.reflect.Method.getParameterTypes(Method.java:174)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.Class.getDeclaredMethods(Class.java:772)
08-21 18:20:58.175 E/Xposed  ( 5970):   at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:249)
08-21 18:20:58.175 E/Xposed  ( 5970):   at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:286)
08-21 18:20:58.175 E/Xposed  ( 5970):   at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:949)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.jt5.xposed.chromepie.Controller.getCurrentTab(Controller.java:135)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.jt5.xposed.chromepie.Controller.getThemeColor(Controller.java:818)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.jt5.xposed.chromepie.PieControl.initColorHooks(PieControl.java:287)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.jt5.xposed.chromepie.PieControl.access$000(PieControl.java:53)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.jt5.xposed.chromepie.PieControl$1.afterHookedMethod(PieControl.java:253)
08-21 18:20:58.175 E/Xposed  ( 5970):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
08-21 18:20:58.175 E/Xposed  ( 5970):   at org.chromium.chrome.browser.ChromeTabbedActivity.initializeUI(<Xposed>)
08-21 18:20:58.175 E/Xposed  ( 5970):   at org.chromium.chrome.browser.ChromeTabbedActivity.finishNativeInitialization(ChromeTabbedActivity.java:280)
08-21 18:20:58.175 E/Xposed  ( 5970):   at org.chromium.chrome.browser.init.ChromeBrowserInitializer$7.initFunction(ChromeBrowserInitializer.java:217)
08-21 18:20:58.175 E/Xposed  ( 5970):   at org.chromium.chrome.browser.init.ChromeBrowserInitializer$1NativeInitTask.run(ChromeBrowserInitializer.java:152)
08-21 18:20:58.175 E/Xposed  ( 5970):   at android.os.Handler.handleCallback(Handler.java:739)
08-21 18:20:58.175 E/Xposed  ( 5970):   at android.os.Handler.dispatchMessage(Handler.java:95)
08-21 18:20:58.175 E/Xposed  ( 5970):   at android.os.Looper.loop(Looper.java:135)
08-21 18:20:58.175 E/Xposed  ( 5970):   at android.app.ActivityThread.main(ActivityThread.java:5254)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.reflect.Method.invoke(Native Method)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.reflect.Method.invoke(Method.java:372)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
08-21 18:20:58.175 E/Xposed  ( 5970):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
08-21 18:20:58.175 E/Xposed  ( 5970):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
08-21 18:20:58.175 E/Xposed  ( 5970): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.assist.AssistContent" on path: DexPathList[[zip file "/data/app/com.chrome.beta-1/base.apk"],nativeLibraryDirectories=[/data/app/com.chrome.beta-1/lib/arm, /vendor/lib, /system/lib]]
08-21 18:20:58.175 E/Xposed  ( 5970):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-21 18:20:58.175 E/Xposed  ( 5970):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-21 18:20:58.175 E/Xposed  ( 5970):   at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
08-21 18:20:58.175 E/Xposed  ( 5970):   ... 27 more
08-21 18:20:58.175 E/Xposed  ( 5970):   Suppressed: java.lang.ClassNotFoundException: android.app.assist.AssistContent
08-21 18:20:58.175 E/Xposed  ( 5970):       at java.lang.Class.classForName(Native Method)
08-21 18:20:58.175 E/Xposed  ( 5970):       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-21 18:20:58.175 E/Xposed  ( 5970):       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-21 18:20:58.175 E/Xposed  ( 5970):       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-21 18:20:58.175 E/Xposed  ( 5970):       ... 29 more
08-21 18:20:58.175 E/Xposed  ( 5970):   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

This worked fine until the most recent Chrome Beta update and [this](https://chromium.googlesource.com/chromium/src.git/+/a8eb4d62dde410cb13dad0d9845364d2d5cbc37f%5E%21/chrome/android/java/src/org/chromium/chrome/browser/ChromeActivity.java) seems to be the commit which added the `AssistContent` reference.
I've tried building my module using the API level 23 build tools but I still get the same error, is this caused by Xposed being compiled for SDK 22, not 23? Is there any way to resolve this issue?

Thanks.

**Comment by rovo89** [comment] 2015-08-23 09:51
First of all: This version isn't official, so I can give only limited support for it. Anyway, I'll give it a try.

> is this caused by Xposed being compiled for SDK 22, not 23

XposedBridge.jar is compiled for SDK15, and this doesn't mean that it can only use classes that were known for this particular SDK.

Have you verified that the `android.app.assist.AssistContent` is actually included in `/data/app/com.chrome.beta-1/base.apk`? There are cases (like in #30) where the class loader is enhanced with further files later. If you try to access classes before this was done, it will fail. You might want to try this: https://github.com/rovo89/XposedBridge/issues/30#issuecomment-68488797

**Comment by JayT5** [comment] 2015-08-24 00:57
Okay, but I’ve also tried it using the official version on 5.0 and still get the same error.

> Have you verified that the android.app.assist.AssistContent is actually included in /data/app/com.chrome.beta-1/base.apk?

As `AssistContent` is part of the Android API, it shouldn’t be included in the Chrome apk, right?

> There are cases where the class loader is enhanced with further files later...

Chrome isn’t a multidex app (there’s only one classes.dex file when viewing the apk as an archive, I assume this is how you check?), so would this still be relevant? But currently I hook Chrome in `onStart` which I think executes after `attach`, so surely the class loader would have had enough time to fully initialise by then anyway?

I’ve done some tests and found that this produces the same error on LP (but works on M):

``` java
import android.app.Activity;
import android.app.assist.AssistContent;
import android.os.Bundle;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getClass().getDeclaredMethods();
    }

    @Override
    public void onProvideAssistContent(AssistContent outContent) {
        //
    }

}

```

The `getDeclaredMethods` call throws the same error because the `AssistContent` parameter of `onProvideAssistContent` cannot be resolved. So if you were to call any other method in the activity using a separate Xposed module (with the `getDeclaredMethods` call removed), the same crash would occur because Xposed also calls `getDeclaredMethods` to find the method to call. I think this is essentially what's happening with my module & Chrome.

Does this make sense, or am I missing something?

**Comment by rovo89** [comment] 2015-08-25 11:00
OK, that makes sense. It's hard to say which component is not behaving correctly here. This class is partly invalid because it contains references to another class that cannot be resolved on LP. Java/ART tries to ignore that as long as it can, but once you try to call the method or want to retrieve more information about it, it's forced to have a closer look and will crash while resolving the method.

No idea what I could do about this. The error isn't caused by Xposed, and even `getDeclaredMethods` can't be blamed. What else should it do? It has to return a reference to the method, which includes references to parameter types, which aren't completely available. Not sure if it would work to retrieve a reference to single method you want to call directly, probably not.

**Closed as completed by rovo89** 2015-08-25 11:00 UTC
Labels: invalid
